monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S32LE"
        audio.rate = 48000
        audio.allowed-rates = [ 44100, 48000, 88200, 96000, 176400, 192000 ]
        resample.quality = 10
      }
    }
  }
]
